{% set python_min = "3.11" %}
{% set name = "flox" %}
{% set version = "0.11.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/61/fd/94b6e6dba647c062434f21b40efe800ca3fed2292856f82c816a8a626b97/flox-{{ version }}.tar.gz
  sha256: ca48d391e4a06cdf1c24368bf73114191851149611a5b318d82436fa713efdf0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools_scm >=7
    - numpy >=1.26
    - numpy_groupies >=0.9.19
    - pandas >=2.1
    - packaging >=21.3
    - toolz
    - scipy >=1.12
  run:
    - packaging >=21.3
    - numpy >=1.26
    - numpy_groupies >=0.9.19
    - pandas >=2.1
    - python >={{ python_min }}
    - toolz
    - scipy >=1.12
  run_constrained:
    - numbagg >=0.6

test:
  imports:
    - flox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xarray-contrib/flox
  summary: Fast & furious GroupBy operations for dask.array
  license: Apache-2.0
  license_file: LICENSE

  doc_url: https://flox.readthedocs.io/
  dev_url: https://github.com/dcherian/flox

extra:
  recipe-maintainers:
    - dcherian
