{% set python_min = "3.10" %}
{% set name = "flox" %}
{% set version = "0.10.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 161a45b9bd053e501781b7081db15dbb61e045b2fed72f8c852fe2569ce5339e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools_scm >=7
    - numpy >=1.22
    - numpy_groupies >=0.9.19
    - pandas >=1.5
    - packaging >=21.3
    - toolz
    - scipy >=1.9
  run:
    - packaging >=21.3
    - numpy >=1.22
    - numpy_groupies >=0.9.19
    - pandas >=1.5
    - python >={{ python_min }}
    - toolz
    - scipy >=1.9
  run_constrained:
    - numbagg >=0.6

test:
  imports:
    - flox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xarray-contrib/flox
  summary: Fast & furious GroupBy operations for dask.array
  license: Apache-2.0
  license_file: LICENSE

  doc_url: https://flox.readthedocs.io/
  dev_url: https://github.com/dcherian/flox

extra:
  recipe-maintainers:
    - dcherian
