{% set python_min = "3.11" %}
{% set name = "flox" %}
{% set version = "0.10.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/7d/4d/93cbe6588aa434173ba5204e3a8b70587a46be10daff0a393c89a1770c34/flox-{{ version }}.tar.gz
  sha256: bb3e7a249dcb4b45bdd8320f9130a1117dc58b9ce6a1e8140b4a20961d2eab03

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools_scm >=7
    - numpy >=1.26
    - numpy_groupies >=0.9.19
    - pandas >=2.1
    - packaging >=21.3
    - toolz
    - scipy >=1.12
  run:
    - packaging >=21.3
    - numpy >=1.26
    - numpy_groupies >=0.9.19
    - pandas >=2.1
    - python >={{ python_min }}
    - toolz
    - scipy >=1.12
  run_constrained:
    - numbagg >=0.6

test:
  imports:
    - flox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xarray-contrib/flox
  summary: Fast & furious GroupBy operations for dask.array
  license: Apache-2.0
  license_file: LICENSE

  doc_url: https://flox.readthedocs.io/
  dev_url: https://github.com/dcherian/flox

extra:
  recipe-maintainers:
    - dcherian
