{% set python_min = "3.11" %}
{% set name = "flox" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/b2/0a/c87438feba1b0e8cb65c8cc2a1de3af18804c81e22c268e7afcf954bf17e/flox-{{ version }}.tar.gz
  sha256: 0a53909bb8929ad8d1dc89a2153144531fd5f18b8106c8bbb4a30151f458b029

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools_scm >=7
    - numpy >=1.26
    - numpy_groupies >=0.9.19
    - pandas >=2.1
    - packaging >=21.3
    - toolz
    - scipy >=1.12
  run:
    - packaging >=21.3
    - numpy >=1.26
    - numpy_groupies >=0.9.19
    - pandas >=2.1
    - python >={{ python_min }}
    - toolz
    - scipy >=1.12
  run_constrained:
    - numbagg >=0.6

test:
  imports:
    - flox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xarray-contrib/flox
  summary: Fast & furious GroupBy operations for dask.array
  license: Apache-2.0
  license_file: LICENSE

  doc_url: https://flox.readthedocs.io/
  dev_url: https://github.com/dcherian/flox

extra:
  recipe-maintainers:
    - dcherian
