{% set python_min = "3.11" %}
{% set name = "flox" %}
{% set version = "0.10.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/74/33/ec88ba3dfe28c04916d3c3a59798eec36dbd708bb6d1b9b4328139962e12/flox-{{ version }}.tar.gz
  sha256: f7a4ecd5e1f75ce2f9f8a51761341d33600df1269f9cd8f17ab38313560331bd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61
    - setuptools_scm >=7
    - numpy >=1.26
    - numpy_groupies >=0.9.19
    - pandas >=2.1
    - packaging >=21.3
    - toolz
    - scipy >=1.12
  run:
    - packaging >=21.3
    - numpy >=1.26
    - numpy_groupies >=0.9.19
    - pandas >=2.1
    - python >={{ python_min }}
    - toolz
    - scipy >=1.12
  run_constrained:
    - numbagg >=0.6

test:
  imports:
    - flox
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/xarray-contrib/flox
  summary: Fast & furious GroupBy operations for dask.array
  license: Apache-2.0
  license_file: LICENSE

  doc_url: https://flox.readthedocs.io/
  dev_url: https://github.com/dcherian/flox

extra:
  recipe-maintainers:
    - dcherian
