conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
bot:
    # only automerge on successful version PRs, migrations are not automerged
    automerge: 'version'
    inspection: update-grayskull  # update recipe using only grayskull
    version_updates:
      exclude:
        - '9.11'
